package SharedClasses.Communication;

/**
 * Created by tiber on 4/14/2016.
 */
public enum RequestedAction {
	GIVE_LOCATION,
	GET_CLIENTS_FOR_SUPERVISOR,
	GET_LATEST_LOCATION_OF_CLIENT,
	GIVE_RECEIVED_SMS,
	GET_SMS_GROUPS_OF_CLIENT,
	GIVE_SENT_SMS,
	ADD_CLIENT,
	DEACTIVATE_CLIENT,
	GET_CONVERSATION,
}
